apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apiservices.apiservice.ligangty.github.com
spec:
  group: apiservice.ligangty.github.com
  names:
    kind: APIService
    listKind: APIServiceList
    plural: apiservices
    singular: apiservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: APIService is the Schema for the apiservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: APIServiceSpec defines the desired state of APIService
          properties:
            config-map:
              description: ConfigMap is the the config map name to retrieve message
                body
              type: string
            size:
              description: Size is the size of the memcached deployment
              format: int32
              type: integer
          required:
          - config-map
          - size
          type: object
        status:
          description: APIServiceStatus defines the observed state of APIService
          properties:
            nodes:
              description: Nodes are the names of the memcached pods
              items:
                type: string
              type: array
              x-kubernetes-list-type: set
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
