apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-service
  template:
    metadata:
      labels:
        name: api-service
    spec:
      serviceAccountName: api-service
      containers:
        - name: api-service
          # Replace this with the built image name
          image: quay.io/ligangty/apiservice-operator:latest
          command:
          - api-service
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "api-service"
