apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apiservice-operator
  template:
    metadata:
      labels:
        name: apiservice-operator
    spec:
      serviceAccountName: apiservice-operator
      containers:
        - name: apiservice-operator
          # Replace this with the built image name
          image: quay.io/ligangty/apiservice-operator:latest
          command:
          - apiservice-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apiservice-operator"
