apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apiservice.ligangty.github.com/v1alpha1",
          "kind": "ApiService",
          "metadata": {
            "name": "api-service"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: api-service.v
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ApiService is the Schema for the apiservices API
      kind: ApiService
      name: apiservices.apiservice.ligangty.github.com
      version: v1alpha1
  displayName: Api Service
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: apiservice-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: apiservice-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: apiservice-operator
            spec:
              containers:
              - command:
                - apiservice-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: apiservice-operator
                image: quay.io/ligangty/apiservice-operator:latest
                imagePullPolicy: Always
                name: apiservice-operator
                resources: {}
              serviceAccountName: apiservice-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - api-service
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - apiservice.ligangty.github.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: api-service
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.0.0
